# Configuração do Cloud Build para o projeto
# Este arquivo especifica como fazer o build e deploy da aplicação

steps:
  # Step 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:latest'
      - '.'
    dir: 'vale-refeicao-ia'  # IMPORTANTE: Define o diretório de contexto
    
  # Step 2: Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:$COMMIT_SHA'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:latest'
    
  # Step 3: Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crmia-agente-autonomo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'

# Imagens geradas
images:
  - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/crmia-agente-autonomo:latest'

# Opções de build
options:
  machineType: 'E2_HIGHCPU_8'  # Máquina mais potente para build mais rápido
  timeout: '1200s'  # 20 minutos de timeout
  logging: CLOUD_LOGGING_ONLY

# Variáveis substituídas automaticamente:
# $PROJECT_ID - ID do projeto Google Cloud
# $COMMIT_SHA - Hash do commit Git
# $BRANCH_NAME - Nome da branch
