# Streamlit Configuration
# https://docs.streamlit.io/library/advanced-features/configuration

[server]
# Tamanho máximo de upload (em MB)
# Cloud Run tem limite de 32MB, configurando 30MB para segurança
maxUploadSize = 30

# Timeout para requisições (em segundos)
maxMessageSize = 30

# Habilitar CORS
enableCORS = false
enableXsrfProtection = false

[browser]
# Não coletar estatísticas de uso
gatherUsageStats = false

[theme]
# Tema padrão
base = "light"