# Streamlit Configuration
# https://docs.streamlit.io/library/advanced-features/configuration

[server]
# Tamanho máximo de upload (em MB)
# Com HTTP/2 no Cloud Run, podemos usar limite maior
maxUploadSize = 500

# Timeout para requisições (em segundos)
maxMessageSize = 300

# Habilitar CORS
enableCORS = false
enableXsrfProtection = false

# Configurações para melhor performance
headless = true
runOnSave = false

[browser]
# Não coletar estatísticas de uso
gatherUsageStats = false

[theme]
# Tema padrão
base = "light"