# Streamlit Configuration
# https://docs.streamlit.io/library/advanced-features/configuration

[server]
# Tamanho máximo de upload (em MB)
# Testando limite muito alto para identificar onde está a real limitação
maxUploadSize = 1000

# Timeout para requisições (em segundos)  
maxMessageSize = 1000

# Habilitar CORS
enableCORS = false
enableXsrfProtection = false

# Força HTTP/2
headless = true

# Configurações para melhor performance
headless = true
runOnSave = false

[browser]
# Não coletar estatísticas de uso
gatherUsageStats = false

[theme]
# Tema padrão
base = "light"