# Streamlit Configuration
# https://docs.streamlit.io/library/advanced-features/configuration

[server]
# Tamanho máximo de upload (em MB)
# Com Cloud Storage, podemos aceitar até 500MB
maxUploadSize = 500

# Timeout para requisições (em segundos)
maxMessageSize = 500

# Habilitar CORS
enableCORS = false
enableXsrfProtection = false

[browser]
# Não coletar estatísticas de uso
gatherUsageStats = false

[theme]
# Tema padrão
base = "light"